### PR TITLE
Keyboardshortcuts

### PR DESCRIPTION
**Pull request by Steedalion**
Added keyboard shortcuts 
- indexed as Appendix F
- Populated the chapters with LXQT Global-keys and Openbox keyboard shortcuts
- Added openbox keys as a table in external file
Made minor changes to Shortcut keys section in chapter 3.

### CODE REVIEW

**Comment by Steedalion** [comment]
Hi Simon, the current application menu windows key is clashing with the resize windows in openbox keys.
I'm not sure if this has come up as a bug but I've made reference to it in Appendix F as an example.

Thanks,

**Comment by tsimonq2** [comment]
Shoot, I think I merged the wrong branch, sorry.

In any case:
```
reading sources... [100%] index                                                                                                                                                                                                              
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:122: WARNING: Inline strong start-string without end-string.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:121: WARNING: Definition list ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:122: WARNING: Block quote ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:130: WARNING: Inline strong start-string without end-string.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:129: WARNING: Definition list ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:130: WARNING: Block quote ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:143: WARNING: Inline strong start-string without end-string.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:137: WARNING: Definition list ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:138: WARNING: Block quote ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:140: WARNING: Unexpected indentation.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:142: WARNING: Definition list ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:143: WARNING: Block quote ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:151: WARNING: Inline strong start-string without end-string.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:150: WARNING: Definition list ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:151: WARNING: Block quote ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:163: WARNING: Inline strong start-string without end-string.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:158: WARNING: Definition list ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:159: WARNING: Block quote ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:161: WARNING: Unexpected indentation.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:163: WARNING: Definition list ends without a blank line; unexpected unindent.
/srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst:164: WARNING: Block quote ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /srv/manual/lubuntu-manual/source/F/keyboard_shorcuts.rst: WARNING: document isn't included in any toctree
/srv/manual/lubuntu-manual/source/F/openbox_keyboard.rst: WARNING: document isn't included in any toctree
```

**Comment by Steedalion** [comment]
I can't be sure if this fixed the error but I did what I think would fix it. The final line refers to a file that is referenced in another file so it will not appear in toc.

**Comment by tsimonq2** [comment]
Fixed and merged, thanks!

**Pull request merged**
